@HostAddress = http://localhost:5271

GET {{HostAddress}}/api/product/getproducts
Accept: application/json

###

POST {{HostAddress}}/api/product/getfilterproduct
Accept: application/json
Content-Type: application/json

{
      "name" : "rise"
}

###